version: '3.8'

services:
  yii2:
    image: {{ dockerhub_username }}/yii2app:latest
    build: .
    ports:
      - "8080:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app_net

networks:
  app_net:
    driver: overlay